apiVersion: 1

policies:
  - orgId: 1
    receiver: n8n-webhook-error
    group_by:
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    routes:
      - receiver: n8n-webhook-warn
        matchers:
          - "level=warn"
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
      - receiver: n8n-webhook-info
        matchers:
          - "level=info"
        group_wait: 30s
        group_interval: 24h
        repeat_interval: 24h
