apiVersion: 1

policies:
  - orgId: 1
    receiver: n8n-webhook-error
    group_by:
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    routes:
      - receiver: n8n-webhook-admin
        matchers:
          - name: channel
            value: admin
            matchType: =
      - receiver: n8n-webhook-ai
        matchers:
          - name: channel
            value: ai
            matchType: =
      - receiver: n8n-webhook-backend
        matchers:
          - name: channel
            value: backend
            matchType: =
