global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "pocat-backend"
    static_configs:
      - targets: ["pocat-backend:8080"]
  - job_name: "pocat-batch"
    static_configs:
      - targets: [ "pocat-batch:8081" ]
  - job_name: "pocat-db"
    static_configs:
      - targets: [ "pocat-db:3306" ]

# es, kafka 등등